export default [
  {
    property_id: 1,
    images: ["pic1prop1.jpeg", "pic2prop1.jpeg", "pic3prop1.jpeg"],
    propertyType: "Apartment",
    priceInBhd: "400",
    name: "Sea view apartment",
    description: "Sea view apartment with many....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "Abraj Al Lulu, Manama, Capital Governate",
    bedrooms: "8",
    bathrooms: "8",
    propertyArea: "736",
    postDate: "5/12/2022",
    phoneNumber: "97333344444"
  },
  {
    property_id: 2,
    images: ["pic4prop2.jpeg", "pic5prop2.jpg", "pic6prop2.jpeg"],
    propertyType: "Villa",
    priceInBhd: "600",
    name: "Good view villa",
    description: "Sea view VILLA with many....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "in front of salmania, Manama, Capital Governate",
    bedrooms: "10",
    bathrooms: "14",
    propertyArea: "750",
    postDate: "8/12/2022",
    phoneNumber: "97322222222"
  },
  {
    property_id: 3,
    images: ["pic7prop3.jpeg", "pic8prop3.jpeg", "pic9prop3.jpeg"],
    propertyType: "Villa",
    priceInBhd: "600",
    name: "villa in the heart of manama",
    description: "villa 2, prop 3....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "villa 2, Manama, Capital Governate",
    bedrooms: "3",
    bathrooms: "5",
    propertyArea: "751",
    postDate: "8/12/2022",
    phoneNumber: "97333333333"
  },
  {
    property_id: 4,
    images: ["pic10prop4.jpeg", "pic11prop4.jpeg", "pic12prop4.jpeg"],
    propertyType: "Apartment",
    priceInBhd: "200",
    name: "Sea view villa",
    description: "Sea view VILLA with many....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "in front of salmania, Manama, Capital Governate",
    bedrooms: "10",
    bathrooms: "14",
    propertyArea: "752",
    postDate: "8/12/2022",
    phoneNumber: "97322222222"
  },
  {
    property_id: 5,
    images: ["pic13prop5.jpg", "pic14prop5.jpg", "pic15prop5.jpg"],
    propertyType: "Apartment",
    priceInBhd: "300",
    name: "Sea view apartment",
    description: "Sea view APARTMENT with many....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "in front of salmania, Manama, Capital Governate",
    bedrooms: "4",
    bathrooms: "6",
    propertyArea: "754",
    postDate: "9/12/2022",
    phoneNumber: "97355555555"
  },
  {
    property_id: 6,
    images: ["pic16prop6.jpeg", "pic17prop6.jpeg", "pic18prop6.jpeg"],
    propertyType: "Villa",
    priceInBhd: "500",
    name: "good looking villa",
    description: "Sea view VILLA with many....slice method used to truim the string to 11 chars, so 2 lines on md screen. otherwise img does not fit card",
    location: "in front of salmania, Manama, Capital Governate",
    bedrooms: "9",
    bathrooms: "11",
    propertyArea: "756",
    postDate: "10/12/2022",
    phoneNumber: "97366666666"
  }
]